services:
  - type: web
    name: listicle-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /

  - type: pserv
    name: listicle-db
    env: postgresql
    plan: free
    region: oregon
